name: install ts-module
on:
  pull_request:
    branches:
      
      - integration
jobs:
  install:
    name: install ts-module
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
      - run: npm ci
      - run: npm install poc-semantic-release-ll@integration
      