name: install ts-module
on:
  pull_request:
    branches:
      - integration
jobs:
  install:
    name: install ts-module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ts-model integration
        run: npm install poc-semantic-release-ll@integration
      - name: Commit and create PR 🔀
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'build(deps): Upgrade NPM packages (automated)'
          branch: 'build-deps-upgrade-npm-packages-automated'
          commit-message: 'build(deps): upgrade NPM packages (automated)'
          base: 'integration'
