name: update library on integration
on:
  pull_request:
    branches:
      - integration
jobs:
  install:
    name: update library on integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ts-model integration
        run: npm install poc-semantic-release-ll@integration
      - name: Commit and create PR 🔀
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Upgrade library to integration version'
          branch: 'upgrade-library-integration-automated'
          commit-message: 'build(deps): upgrade NPM packages (automated)'
          base: 'integration'
