name: update library on main
on:
  pull_request:
    branches:
      - master
jobs:
  install:
    name: update library on main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ts-model master
        run: npm install poc-semantic-release-ll@latest
      - name: Commit and create PR 🔀
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Upgrade library to mastaer version'
          branch: 'upgrade-library-master-automated'
          commit-message: 'build(deps): upgrade NPM packages (automated)'
          base: 'master'
