name: update library on master
on:
  push:
    branches: ['master']
jobs:
  install:
    name: update library on master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
       
      - name: set git remote
        run: git remote set-url origin "https://x-access-token:${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
      - name: show remotes
        run: git remote -v
      - name: fetch
        run: git fetch origin master
      - name: git checkout
        run: git checkout master
      - name: extract new_lib
        id: new_lib
        run: |

          echo "##[set-output name=lib_name;]$(git diff origin/master~1 origin/master package.json | grep  -e 'poc-semantic-release-ll' | grep '^[+][^+]')"    
          # echo ${{ steps.new_lib.outputs.lib_name }}
      - name: lib
        run: echo ${{ steps.new_lib.outputs.lib_name }}
      - name: install library
        if: | 
            contains(steps.new_lib.outputs.lib_name, 'poc-semantic-release-ll') && 
            ( contains(steps.new_lib.outputs.lib_name, 'staging') ||
              contains(steps.new_lib.outputs.lib_name, 'integration') ) 
        run: |
            npm install poc-semantic-release-ll
            git add .
            git config --global user.email "lisandrolan@gmail.com"
            git config --global user.name "Lisandro Langenauer"
            git commit -m "generated"
            git push 
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
