name: install ts-module
on:
  push:
    branches:
      
      - staging
jobs:
  install:
    name: install ts-module
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run:  run: |
          npm ci
          npm install poc-semantic-release-ll@staging
      