name: install ts-module
on:
  push:
    branches:
      
      - staging
jobs:
  install:
    name: install ts-module
    runs-on: ubuntu-latest
    steps:
      - name: do clean install
        run: npm ci
      - name: install ts-model staging
        run: npm install poc-semantic-release-ll@stagings

      