name: update library on master
on:
  pull_request:
    branches:
      - master
jobs:
  install:
    name: update library on master
    runs-on: ubuntu-latest
       steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set git remote
        run: git remote set-url origin "https://x-access-token:${{ secrets.PY_REPO_GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
      - name: show remotes
        run: git remote -v
      - name: extract old_lib
        id: old_lib
        run: |
          echo "##[set-output name=lib_name;]$(git diff package.json | grep  -e 'poc-semantic-release-ll' | grep '^[-][^-]')"    
      - name: extract new_lib
        id: new_lib
        run: |
          echo "##[set-output name=lib_name;]$(git diff package.json | grep  -e 'poc-semantic-release-ll' | grep '^[+][^+]')"    
      - name: Extract branch name on pull request
        if: github.event_name == 'pull_request'
        run: echo "::set-output name=branch::$(echo ${GITHUB_HEAD_REF})"
        id: extract_branch
      - name: fetch
        run: git fetch --depth=50 origin master
      - name: install library
        if: | 
            steps.extract_branch.outputs.branch == 'master' && 
            contains(steps.new_lib.outputs.lib_name, 'poc-semantic-release-ll') && 
            !contains(steps.new_lib.outputs.lib_name, 'staging') && 
            !contains(steps.old_lib.outputs.lib_name, 'integration')
        run: |
            npm install poc-semantic-release-ll
            git config user.email "merge-broker@no-reply.papayaglobal.com"
            git config user.name "Merge Broker Workflow"
            git add .
            git commit -m "generated"
            git push origin HEAD:master

