name: update library on staging
on:
  push:
    branches: ['staging']
jobs:
  install:
    name: update library on staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set git remote
        run: git remote set-url origin "https://x-access-token:${{ secrets.PY_REPO_GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
      - name: show remotes
        run: git remote -v
      - name: fetch
        run: git fetch origin staging
      - name: git checkout
        run: git checkout staging
      - name: extract new_lib
        id: new_lib
        run: |
          echo "##[set-output name=lib_name;]$(git diff origin/staging~1 origin/staging package.json | grep  -e 'poc-semantic-release-ll' | grep '^[+][^+]')"    
          # echo ${{ steps.new_lib.outputs.lib_name }}
      - name: lib
        run: echo ${{ steps.new_lib.outputs.lib_name }}
      - name: install library
        if: | 
            contains(steps.new_lib.outputs.lib_name, 'poc-semantic-release-ll') && 
            !contains(steps.new_lib.outputs.lib_name, 'staging') 
        run: |
            npm install poc-semantic-release-ll@staging
            git config user.email "lisandrolan@gmail.com"
            git config user.name "Merge Broker Workflow"
            git add .
            git commit -m "generated"
            git push origin HEAD:staging
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
